#!/usr/bin/env bash
# script that will display information about subdomains
domain_info () {
    dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$2.$1/$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    domain_info "$1" "$2"
else
    domain_info "$1" "www"
    domain_info "$1" "lb-01"
    domain_info "$1" "web-01"
    domain_info "$1" "web-02"
fi
