#!/usr/bin/env bash
# Installs and sets up NGINX
apt-get -y update
apt-get -y install nginx
sed -i "21s/^listen .*/listen 80" /etc/nginx/sites-enabled/defult
sudo ufw allow "Nginx HTTP"
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start