#!/usr/bin/env bash
# Sets up a brand new nginx server with a redirect page.
apt-get update
apt-get install -y nginx
service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx restart