#!/usr/bin/env bash
# # Run as root, echos pid into /var/run and traps then runs an infinite loop

FILEPATH=/var/run/myscript.pid
echo $$ > $FILEPATH

trap 'echo "I hate the kill command"; rm ${FILEPATH}; exit 0' SIGTERM
trap 'echo "Y U no love me?!"; rm ${FILEPATH}; exit 0' SIGINT

while :
do
    echo 'To infinity and beyond'
    sleep 2
done