#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

while [[ $counter -lt 10 ]]
do
    echo "Best School"
    if [[ $counter -eq 8 ]]
    then
        echo "Hi"
    fi
    ((counter++))
done