#!/usr/bin/env bash
# displays Best School 10 times.
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration

while [[ $counter -lt 10 ]]
do
    if [[ $counter -eq 3 ]]
    then
        echo "bad luck"
    elif [[ $counter -eq 7 ]]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done