#!/usr/bin/env bash
# This script that displays the time for 12 hours and 59 minutes

count=0
minutes=0
while true
do      
    case $minutes in
        0)
            echo "Hour: ${minutes}"
        ;;
        60)
            echo "Hour: ${minutes}"
            minutes=1
            ((count++))
        ;;
        *)
    esac
        
    if [[ $count -eq 13 ]]
    then
        break
    else
        echo "${minutes}"
        if [[ $minutes -eq 59 && $count -eq 12 ]]
        then
            break
        fi
    fi

    ((minutes++))
done