#!/usr/bin/env bash
# This script that displays the time for 12 hours and 59 minutes

hour=0
minutes=0
while true
do      
    case $minutes in
        0)
            echo "Hour: ${hour}"
        ;;
        60)
            ((hour++))
            echo "Hour: ${hour}"
            minutes=1
        ;;
        *)
    esac

    if [ ${minutes} -eq 59 ] && [ ${hour} -eq 12 ]
    then
        echo "${minutes}"
        break
    elif [ ${hour} -eq 13 ]
    then
        break
    else
        echo "${minutes}"
    fi

    ((minutes++))
done