#!/usr/bin/env bash
# This script gives information about the school file.

FILENAME=school
if [[ -e ${FILENAME} ]]
then
    echo "school file exists"
elif [[ ! -e ${FILENAME} ]]
then
    echo "school file does not exist"
fi

if [[ ! -s ${FILENAME} && -e ${FILENAME} ]]
then
    echo "school file is empty"
elif [[ -s ${FILENAME} && -e ${FILENAME} ]]
then
    echo "school file is not empty"
fi

if [[ -f ${FILENAME} && -e ${FILENAME} ]]
then
    echo "school is a regular file"
fi