#!/usr/bin/env bash
# Gives you information about the school file.

filename=school
if [[ -e ${filename} ]]
then
    echo "school file exists"
elif [[ ! -e ${filename} ]]
then
    echo "school file does not exist"
fi

if [[ ! -s ${filename} && -e ${filename} ]]
then
    echo "school file is empty"
elif [[ -s ${filename} && -e ${filename} ]]
then
    echo "school file is not empty"
fi

if [[ -f ${filename} && -e ${filename} ]]
then
    echo "school is a regular file"
fi