#!/usr/bin/env bash
# Fixes server bug
# script should run the whoami command under the user passed 
# as an argument and make sure to try your script by passing different users
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx start
